apiVersion: apps/v1
kind: Deployment
metadata:
  name: v1-catalogues
  namespace: api
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: v1-catalogues
      cluster: dt
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        fluentbit.io/parser: json
      creationTimestamp: null
      labels:
        app: v1-catalogues
        cluster: dt
    spec:

