---
apiVersion: v1
kind: Pod
metadata:
  name: mydep
spec:
  containers:
    - name: foo
      image: alpine
      command: ["/bin/bash"]
      args:
        - -c
        - |
          echo "Use the ${sops:secret}"

