#!/usr/bin/env /usr/bin/python3

import pkg_resources
pkg_resources.require('PyYAML>=5.1.1')

import sys
import yaml

with open(sys.argv[1], 'r') as stream:
    try:
        data = yaml.safe_load(stream)
    except yaml.YAMLError as exc:
        print("Error parsing CertificateTransformer input", file=sys.stderr)
if 'except' not in data:
    data['except'] = []

try:
    for yaml_input in yaml.safe_load_all(sys.stdin):
        if yaml_input['kind'] == 'Certificate':
            if (yaml_input['apiVersion'] == 'cert-manager.io/v1alpha2' or
              yaml_input['apiVersion'] == 'certmanager.k8s.io/v1alpha1'):
                if "namespace" in yaml_input['metadata']:
                    name = yaml_input['metadata']['namespace'] + '/' + yaml_input['metadata']['name']
                else:
                    name = yaml_input['metadata']['name']
                if name not in data['except']:
                    if yaml_input['spec']['issuerRef']['name'] == data['oldIssuer']:
                        yaml_input['spec']['issuerRef']['name'] = data['newIssuer']
        print("---")
        print(yaml.dump(yaml_input, default_flow_style=False))
except yaml.YAMLError as exc:
    print("Error parsing YAML input\n\n%s\n\n" % input, file=sys.stderr)
